### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by 0x8han** [sandrogauci/wafw00f#16]
Hi Sandro , i followed those steps 
hany@HP-Pro:~/toolz$ sudo git clone https://github.com/sandrogauci/wafw00f
Cloning into 'wafw00f'...
remote: Counting objects: 454, done.
remote: Total 454 (delta 0), reused 0 (delta 0), pack-reused 454
Receiving objects: 100% (454/454), 124.68 KiB | 153.00 KiB/s, done.
Resolving deltas: 100% (252/252), done.
Checking connectivity... done.
-----------------
hany@HP-Pro:~/toolz/wafw00f$ sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
---------------------
Thanks

**Comment by sandrogauci** [comment]
you'll need to get setuptools installed. https://pypi.python.org/pypi/setuptools
