### ISSUE TITLE
Version number

### ISSUE THREAD

**Issue by leebaird** [sandrogauci/wafw00f#25]
It would help if you could add a version number and change log. This would make it easier for the Kali Linux dev team to track.

**Comment by sandrogauci** [comment]
Hi Lee, 

Of course it would. We do use version numbers in fact. Check out the [releases](https://github.com/sandrogauci/wafw00f/releases) and also the source code ([here](https://github.com/sandrogauci/wafw00f/blob/master/wafw00f/__init__.py) and [there](https://github.com/sandrogauci/wafw00f/blob/master/wafw00f/main.py#L384)). 

Do you need something else for the Kali team?
